name: Convert Webgame Text to JSON

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run conversion script
        run: |
          python convert_text_to_json.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/aliance_data.json
          git commit -m "Automatický převod Webgame výpisu na JSON" || echo "No changes"
          git push
