name: Convert Webgame Text to JSON

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python convert_text_to_json.py
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/aliance_data.json
          git commit -m "Automatický převod Webgame výpisu na JSON" || echo "No changes"
          git push
