name: Generate Alliance Board

on:
  push:
    paths:
      - 'data/aliance_data.json'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install jinja2
      - run: python main.py
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Automatické generování nástěnky" || echo "No changes"
          git push
